baseURL = "https://blog.davidleen.me/"
languageCode = "en-us"
title = "David Leen"
theme = "PaperMod"

[params]
  defaultTheme = "auto"  # auto, light, or dark
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = false
  showCodeCopyButtons = true
  disableSpecial1stPost = true

  # [[params.socialIcons]]
  # name = "github"
  # url = "https://github.com/dleen"

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
